### ISSUE TITLE
should not be able to play a board after use has given up

### ISSUE THREAD

**Issue by michaelficarra** [fluffynukeit/purescript-puzzler#1]
I can win very easily by giving up, double-clicking a piece, then placing the piece again. I should not be able to modify the board after I press the give up button.

**Comment by fluffynukeit** [comment]
Ah, yep, a good catch.  Although you don't really feel like you won, do you? :)  I'll fix that transition.

You can also "win" by Hinting every piece into position, removing one, then placing it again.

**Comment by michaelficarra** [comment]
That's right, if you hint the last piece, you've neither won nor lost. Maybe you shouldn't be able to do that.

**Comment by fluffynukeit** [comment]
Ok, game state freezes once victory/defeat is established, and hints will have no effect if only 1 piece is left.
